using System.Text;
using System.Threading.RateLimiting; // Added for Rate Limiter
using CarDealershipApi.Middleware;
using CarDealershipApi.Services;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using Serilog;

var builder = WebApplication.CreateBuilder(args);

// ==========================================
// 1. LOGGING SETUP (SERILOG)
// ==========================================
// We replace the default .NET logger with Serilog for better formatting and file writing.
Log.Logger = new LoggerConfiguration()
    .ReadFrom.Configuration(builder.Configuration)
    .CreateLogger();
builder.Host.UseSerilog();

// ==========================================
// 2. CONTROLLER & STRICT XML CONFIGURATION
// ==========================================
builder.Services.AddControllers(options =>
{
    // Forces the API to reject any request that asks for JSON (returns 406 Not Acceptable)
    options.ReturnHttpNotAcceptable = true;
})
.AddXmlSerializerFormatters() // Tells .NET how to serialize/deserialize XML
.ConfigureApiBehaviorOptions(options =>
{
    // By default, .NET returns JSON when a user sends a bad payload (like missing a required field).
    // This override forces those validation errors to return in our strict XML format instead.
    options.InvalidModelStateResponseFactory = context =>
    {
        var xmlError = "<error><code>400</code><message>Validation failed or malformed XML input.</message></error>";
        return new ContentResult
        {
            Content = xmlError,
            ContentType = "application/xml",
            StatusCode = 400
        };
    };
});

// ==========================================
// 3. AUTHENTICATION (JWT) & AUTHORIZATION
// ==========================================
var jwtKey = builder.Configuration["Jwt:Key"] ?? throw new InvalidOperationException("JWT Key is missing");
builder.Services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddJwtBearer(options =>
{
    // The rules for validating a token that a user sends us
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuerSigningKey = true,
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.ASCII.GetBytes(jwtKey)),
        ValidateIssuer = false, // Not checking who created the token (simplified)
        ValidateAudience = false, // Not checking who the token is for (simplified)
        ValidateLifetime = true, // Ensure the token hasn't expired
        ClockSkew = TimeSpan.Zero // Tokens expire exactly at 30 mins, no 5-minute buffer
    };

    // Override default JSON responses for Auth failures so they return as XML
    options.Events = new JwtBearerEvents
    {
        // OnChallenge happens when a user provides NO token or an INVALID token (401)
        OnChallenge = context =>
        {
            context.HandleResponse(); // Stop .NET from sending its default JSON
            context.Response.StatusCode = 401;
            context.Response.ContentType = "application/xml";
            return context.Response.WriteAsync("<error><code>401</code><message>Unauthorized: Invalid credentials or missing token.</message></error>");
        },
        // OnForbidden happens when a user HAS a valid token, but lacks the required Role (403)
        OnForbidden = context =>
        {
            context.Response.StatusCode = 403;
            context.Response.ContentType = "application/xml";
            return context.Response.WriteAsync("<error><code>403</code><message>Forbidden: Insufficient role to access this resource.</message></error>");
        }
    };
});

// ==========================================
// 4. SWAGGER DOCUMENTATION CONFIGURATION
// ==========================================
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "Car Dealership XML API", Version = "v1" });

    // Enable XML Comments reading (This pulls descriptions from the file generated by .csproj)
    var xmlFile = $"{System.Reflection.Assembly.GetExecutingAssembly().GetName().Name}.xml";
    var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
    c.IncludeXmlComments(xmlPath);

    // Add the "Authorize" button in the Swagger UI so we can paste our JWT token
    c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Description = "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
        Name = "Authorization",
        In = ParameterLocation.Header,
        Type = SecuritySchemeType.Http,
        Scheme = "bearer",
        BearerFormat = "JWT"
    });

    // Tell Swagger to apply that token to all endpoints
    c.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "Bearer" }
            },
            Array.Empty<string>()
        }
    });
});

// ==========================================
// 5. DEPENDENCY INJECTION (SERVICE REGISTRATION)
// ==========================================
// Singleton: One instance is shared across the entire app for all users (good for in-memory data)
builder.Services.AddSingleton<UserService>();

// Scoped: A new instance is created once per HTTP request
builder.Services.AddScoped<XmlDataService>();
builder.Services.AddScoped<XsdValidationService>();
builder.Services.AddScoped<XsltTransformationService>();

// HttpClient: Specialized scoped service for making external web calls
builder.Services.AddHttpClient<VinIntegrationService>();

// ==========================================
// 6. SECURITY, HEALTH, & RATE LIMITING
// ==========================================
// Health Checks: Provides a simple endpoint to monitor if the API is online
builder.Services.AddHealthChecks();

// Rate Limiting: Prevents abuse/DDoS by limiting how many requests an IP can make.
builder.Services.AddRateLimiter(options =>
{
    options.GlobalLimiter = PartitionedRateLimiter.Create<HttpContext, string>(httpContext =>
        RateLimitPartition.GetFixedWindowLimiter(
            // Partition by the user's IP address
            partitionKey: httpContext.Connection.RemoteIpAddress?.ToString() ?? "unknown",
            factory: partition => new FixedWindowRateLimiterOptions
            {
                AutoReplenishment = true,
                PermitLimit = 100, // Maximum of 100 requests...
                QueueLimit = 2,    // Allows 2 requests to queue if they exceed the limit
                Window = TimeSpan.FromMinutes(1) // ...per 1-minute window
            }));

    // Return standard XML error format when limit is exceeded
    options.OnRejected = async (context, token) =>
    {
        context.HttpContext.Response.StatusCode = 429;
        context.HttpContext.Response.ContentType = "application/xml";
        await context.HttpContext.Response.WriteAsync("<error><code>429</code><message>Too many requests. Please try again later.</message></error>", token);
    };
});


var app = builder.Build();

// ==========================================
// 7. HTTP REQUEST PIPELINE (MIDDLEWARE)
// ==========================================
// Note: The order of these lines is very important!

// Logs every incoming request method, path, and response status
app.UseSerilogRequestLogging();

// Custom middleware to catch unhandled crashes and return a clean 500 XML error
app.UseMiddleware<GlobalExceptionMiddleware>();

// ONLY enable Swagger in Development. It is completely hidden in Production environments.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(); // Serves the UI at http://localhost:<port>/swagger
}
else
{
    // HTTP STRICT TRANSPORT SECURITY (HSTS): Forces browsers to use HTTPS in Production
    app.UseHsts();
}

//Allow .NET to serve CSS, JS, and HTML from the wwwroot folder
app.UseStaticFiles();

// Redirects all standard HTTP traffic to secure HTTPS
app.UseHttpsRedirection();

// Enables Rate Limiting (Must be placed before Authentication but after Routing)
app.UseRateLimiter();

// Determines WHO the user is based on their token
app.UseAuthentication();
// Determines WHAT the user is allowed to do based on their Role
app.UseAuthorization();

// Routes the request to the correct Controller endpoint
app.MapControllers();

// Maps the health check to a specific URL path
app.MapHealthChecks("/api/v1/health");

// If a user requests a URL that .NET doesn't recognize (like /sales/dashboard),
// it will send them the React index.html file so React Router can handle it.
app.MapFallbackToFile("index.html");

// Starts the application
app.Run();